language: python
cache: pip
python:
- '3.7'
- '3.8'
- '3.9'
before_install:
- openssl aes-256-cbc -K $encrypted_92656c47caa2_key -iv $encrypted_92656c47caa2_iv
  -in .travis.secrets.tar.gz.enc -out .travis.secrets.tar.gz -d
- tar xvzf .travis.secrets.tar.gz
install:
- pip install -U pip
- pip install -U importlib-metadata
- pip uninstall -y six
- pip install six>=1.12.0
- pip install -r requirements-test.txt
- pip install --prefer-binary -e .
script: python setup.py test
