language: python
cache: pip
python:
- '2.7'
- '3.7'
- '3.8'
- '3.9'
- 'pypy'
before_install:
- openssl aes-256-cbc -K $encrypted_92656c47caa2_key -iv $encrypted_92656c47caa2_iv
  -in .travis.secrets.tar.gz.enc -out .travis.secrets.tar.gz -d
- tar xvzf .travis.secrets.tar.gz
install: ./.travis_install_phase.sh
script: python setup.py test
